### ISSUE TITLE
Trouble setting up an environment

### ISSUE THREAD

**Issue by alexkahn** [SmileyChris/django-navtag#4]
Hi!

Been using the project in production for a couple years and I know that you're probably busy but I am trying to get a development environment set up to test this package against python 3.6 and django 1.11. Any pointers would be great - I'm using pyenv which made running tox, let's say, interesting. Any pointers would be great, thanks for making this library.

**Comment by SmileyChris** [comment]
How does pyenv change how tox works since it'll still just use virtualenv?

I've updated the tox.ini a bit anyway to cover Python 3.6. Works fine for me. Also if you make a forked pull request travis will still check it for you even if you're having trouble running the full test runner (you could just run the tests without tox locally to check against your installed version)
